## Week1 Example Env

In [2]:
## !pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/8f/bb/aea1fbeed5b474cb8634364718abe9030d7cc7a30bf51f40bd494bbc89a2/pandas-2.0.3-cp311-cp311-macosx_11_0_arm64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 3.9 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 5.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 6.9 MB/s eta 0:00:0000:0100:01


In [2]:
import torch
import numpy as np

import pandas

In [3]:
a = torch.ones(3)

print(a)

print(    float(   a[1]   )      )

a[2]  =  17.0

print(  a  )

tensor([1., 1., 1.])
1.0
tensor([ 1.,  1., 17.])


In [4]:
print(float(a[1]))

1.0


In [5]:
a[1] = 12
print(a)

tensor([ 1., 12., 17.])


In [6]:
b = np.array([1,5,67,87],dtype = float)
print(b)

[ 1.  5. 67. 87.]


In [7]:
list_of_list = [[1,4,6],[5,3,7],[4,7,78]]
print(np.array(list_of_list))

[[ 1  4  6]
 [ 5  3  7]
 [ 4  7 78]]


In [8]:
b = np.ones((4,6),dtype = int)
print(b)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [9]:
b = np.full((3,5),11)
print(b)

[[11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]]


In [10]:
b = np.arange(1,30,3)
print(b)

[ 1  4  7 10 13 16 19 22 25 28]


In [16]:
b = np.linspace(0,10,4,dtype = int)
print(b)
b.shape

[ 0  3  6 10]


(4,)