In [1]:
import torch

In [2]:
import numpy as np

In [3]:
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [4]:
a[2] = 17
print(a)

tensor([ 1.,  1., 17.])


In [10]:
b = [4.0,1.8,5.0,3.0,2.2,1.5,4.3]

b_t = torch.tensor(b)

print(b_t)

tensor([4.0000, 1.8000, 5.0000, 3.0000, 2.2000, 1.5000, 4.3000])


In [36]:
c = [[2.,5.],[4.0,7.0],[6.,9.]]
# c = b_t.reshape(-1)
print(c)

[[2.0, 5.0], [4.0, 7.0], [6.0, 9.0]]


In [28]:
d = torch.zeros((3,4))

print(d)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [29]:
d[1,1] = 23

print(d)

tensor([[ 0.,  0.,  0.,  0.],
        [ 0., 23.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])


In [31]:
print(d[1,:])

tensor([ 0., 23.,  0.,  0.])


In [37]:
print(d[1,0])

tensor(0.)


In [38]:
print(d.shape)

torch.Size([3, 4])


In [50]:
d_t_new = d[...,None]
print(d_t_new)
print(d_t_new.shape)

tensor([[[ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [23.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.]]])
torch.Size([3, 4, 1])


In [52]:
batch_t = torch.randn(8, 3, 5, 5)
print(batch_t)
print(batch_t.shape)

tensor([[[[-1.1920e+00,  2.2025e-01,  2.0037e+00,  5.4629e-01,  1.8673e+00],
          [-6.1664e-01,  1.6274e+00, -3.2157e-01,  1.1313e-01, -2.9342e-02],
          [ 2.5059e-01,  8.9672e-01, -7.1601e-01, -1.0972e+00,  1.6784e-01],
          [ 1.0428e-01, -1.2606e+00, -1.1808e+00, -4.7830e-01, -1.3720e-01],
          [ 1.4209e-01, -1.1600e+00, -7.3319e-01, -1.1705e-01, -7.0596e-02]],

         [[ 9.6858e-01, -8.5887e-02,  6.4724e-01, -1.2190e-01,  5.8803e-01],
          [ 2.9477e+00, -1.7844e+00,  9.8254e-02,  1.8830e+00,  1.7113e+00],
          [-1.2991e-01, -8.5226e-01,  1.0903e+00, -1.3382e+00, -5.9354e-01],
          [-1.3617e+00,  1.7895e-01, -1.1991e+00,  1.0573e+00,  3.6838e-01],
          [-2.1792e+00, -2.2252e+00, -3.8292e-01, -4.7905e-01,  2.8526e-01]],

         [[ 4.6194e-01, -2.0936e+00,  8.8784e-01,  6.4309e-01,  5.3699e-01],
          [ 7.5404e-01, -6.1285e-02,  8.0338e-01, -6.6086e-01,  7.2514e-01],
          [-5.2573e-01, -3.1567e-01, -4.7429e-01, -9.6827e-01,  8.1903e-

In [59]:
datatype_t = torch.ones(10,2, dtype = torch.double)
datatype_t.dtype

torch.float64

In [63]:
a = torch.ones(3,2)
b = torch.ones(5)
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([1., 1., 1., 1., 1.])


In [65]:
a = [1,4,5,6]
b = [[1,2,3],[4,5,6]]
print(a+b)

[1, 4, 5, 6, [1, 2, 3], [4, 5, 6]]


## Numpy Inter-Operability

In [73]:
points = torch.ones(8,8)
points

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [79]:
points_np = points.numpy()
print(points_np)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
